name: Cron and Push Jobs

on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches:
      - main  # Replace with your branch name if needed

jobs:
  cron_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a cron script
        run: echo "Hello from the cron job!"

  login_to_webpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List directory contents
        run: ls -la
      - name: Run loginscript
        run: |
          echo "Hello, world!"
          ./login.sh