name: Cron and Push Jobs

on:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches:
      - main  # Replace with your branch name if needed

jobs:
  cron_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a cron script
        run: echo "Hello from the cron job!"

  push_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run push script
        run: echo "Hello from the push job!"
        # Add more steps as needed for the push job

  login_to_webpage:
    runs-on: ubuntu-latest
    steps:
      - name: Run loginscript
        run: |
          echo "Hello, world!"
          ./login.sh  # Execute the script directly