name: Cron and Push Jobs

on:
  schedule:
    - cron: "* */48 * * *"
  push:
    branches:
      - main  # Replace with your branch name if needed

jobs:
  cron_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a cron script
        run: ./login.sh